config/routes.rb
Rails.application.routes.draw do
  # See all routes with "rails routes" command in terminal

  # Routes for rails_admin controller
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Routes for reservations controller
  resources :reservations, only: [:show, :new, :create, :edit, :update] do
    # Nested routes for payments controller
    resources :payments, only: [:new, :create]
  end

  # Routes for documents
  resources :documents, only: [:create]

  # Routes for custom users controller (not devise)
  resources :users, only: [:edit, :update]
  post '/create_user_info' => 'users#create_user_info', as: 'create_user_info'
  get '/users/:id/informations' => 'users#user_info', as: 'user_info'

  resources :user_data, only: [:new, :create, :update]
  # Routes for devise (user authentication)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Routes for pages controller
  root to: 'users#tracking'

  get '/tracking' => 'users#tracking', as: 'tracking'
  get '/profile' => 'user_data#profile', as: 'profile'
  get '/suggestions' => 'users#suggestions', as: 'suggestions'
  get '/accomodations' => 'users#accomodations', as: 'accomodations'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :reservation, dependent: :destroy
  has_one :suggestion, dependent: :destroy
  has_one :user_datum, dependent: :destroy
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  mount_uploader :profile_pic, ProfilePicUploader

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.skip_confirmation!
      user.save
    end

    return user
  end

  def has_reservation?
    self.reservation == nil
  end

  def has_user_data?
    self.user_datum == nil
  end

  def has_paid?
    self.reservation.payment_status == "paid"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Facebook')
      end
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:tracking, :suggestions, :accomodations]

  def tracking
    if @user.has_user_data?
      redirect_to new_user_datum_path
    elsif @user.has_reservation?
      redirect_to new_reservation_path(@user)
    elsif !@user.has_paid?
      redirect_to new_reservation_payment_path(current_user.reservation)
    else
      # Set the user's reservation
      @reservation = @user.reservation
    end
  end

  def suggestions
    if @user.has_user_data?
      redirect_to new_user_datum_path
    elsif @user.has_reservation?
      redirect_to new_reservation_path(@user)
    elsif !@user.has_paid?
      redirect_to new_reservation_payment_path(current_user.reservation)
    else
      # Set the user's reservation
      @reservation = @user.reservation
      # Set the suggestion if admin created it
      @diplomas = set_suggestions(@user.suggestion) unless @user.suggestion == nil
    end
  end

    def accomodations
      if @user.has_user_data?
        redirect_to new_user_datum_path
      elsif @user.has_reservation?
        redirect_to new_reservation_path(@user)
      elsif !@user.has_paid?
        redirect_to new_reservation_payment_path(current_user.reservation)
      else
        # Set the user's reservation
        @reservation = @user.reservation
      end
    end

    private

    # Set the user
    def set_user
      @user = current_user
    end

    # Put all 3 or 5 suggestions into an array, practical for suggestion display in dashboard
    def set_suggestions(suggestion)
      diplomas = []

      diplomas << Diploma.find(suggestion.diploma_one_id) unless suggestion.diploma_one_id == nil
      diplomas << Diploma.find(suggestion.diploma_two_id) unless suggestion.diploma_two_id == nil
      diplomas << Diploma.find(suggestion.diploma_three_id) unless suggestion.diploma_three_id == nil
      diplomas << Diploma.find(suggestion.diploma_four_id) unless suggestion.diploma_four_id == nil
      diplomas << Diploma.find(suggestion.diploma_five_id) unless suggestion.diploma_five_id == nil

      return diplomas
    end
  end

app/views/users/accomodations.html.erb
<div id="wrapper" class="toggled">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li><%= link_to "Mon suivi", tracking_path %></li>
      <li><%= link_to "Mon profil", profile_path %></li>
      <li><%= link_to "Mes suggestions", suggestions_path %></li>
      <li><%= link_to "Mon logement", accomodations_path %></li>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="row welcome">
        <h3> Bonjour <%= current_user.first_name %> ! </h3>
      </div>
      <a href="#menu-toggle" class="btn btn-sidebar" id="menu-toggle">Menu</a>
      <div class="container">
        <% if @reservation.pack.sku != 'premium' %>
        <div class="row text-center">
          <h4 class="text-center">Tu veux être sûr(e) de trouver un toît ?</h4>
          <p class='center-align'>Avec le pack premium, nous nous occupons aussi de ton logement !</p>
          <p class='center-align'>Tu peux modifier à tout moment ta réservation.</p>
          <%= link_to 'Modifier ma formule !', edit_reservation_path(@reservation), class: 'btn btn-sidebar' %>
        </div>
        <% end %>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>

app/views/users/suggestions.html.erb
<div id="wrapper" class="toggled">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li><%= link_to "Mon suivi", tracking_path %></li>
      <li><%= link_to "Mon profil", profile_path %></li>
      <li><%= link_to "Mes suggestions", suggestions_path %></li>
      <li><%= link_to "Mon logement", accomodations_path %></li>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="row welcome">
      <h3> Bonjour <%= current_user.first_name %> ! </h3>
    </div>
    <a href="#menu-toggle" class="btn btn-sidebar" id="menu-toggle">Menu</a>
    <div class="container-fluid">
      <% if @user.suggestion == nil %>
        <div class="row text-center">
            <h4 class="text-center">Tes informations ont été enregistrées !</h4>
            <p class='center-align'>Nous établissons une liste de suggestion par rapport aux informations que tu as envoyé.</p>
            <p class='center-align'>Tu recevras un mail dès qu'elle sera disponible !</p>
        </div>
      <% else %>
      <div class="container-fluid">
      <div class="row">
        <% @diplomas.each do |diploma| %>
        <% unless diploma == nil %>
        <div class="col-xs-12">
          <div class="card-suggestions" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= diploma.diploma_photo.url(:standard) %>');">
            <div class="card-category"><%= diploma.discipline %></div>
            <div class="card-description">
              <h2><%= diploma.country %></h2>
              <p><%= diploma.city %></p>
            </div>
            <%= link_to "", diploma.program_website, target: "_blank", class: "card-link" %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      </div>
      <% end %>
    </div>
  </div>
  <!-- /#page-content-wrapper -->
</div>

app/views/users/tracking.html.erb
<div id="wrapper" class="toggled">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li><%= link_to "Mon suivi", tracking_path %></li>
      <li><%= link_to "Mon profil", profile_path %></li>
      <li><%= link_to "Mes suggestions", suggestions_path %></li>
      <li><%= link_to "Mon logement", accomodations_path %></li>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="row welcome">
      <h3> Bonjour <%= current_user.first_name %> ! </h3>
    </div>
    <a href="#menu-toggle" class="btn btn-sidebar" id="menu-toggle">Menu</a>
    <div class="container-fluid">
      <br>
      <% if @reservation.pack.sku == "starter" %>
        <div class="row text-center">
            <h4 class="text-center">Tu veux que nous nous occupions de tout ?</h4>
            <p class='text-center'>Avec le pack Starter Plus, nous gérons tes inscriptions.</p>
            <p class='text-center'>Encore mieux, avec le pack Starter Premium, nous nous occupons aussi de ton logement !</p>
            <p class='text-center'>Si tu veux modifier ta réservation, c'est par là...</p>
            <%= link_to 'Modifier ma formule !', edit_reservation_path(@reservation), class: 'btn btn-sidebar' %>
        </div>
      <% else %>
        <% if @reservation.tracking_status == "paid" %>
        <div class="row text-center">
            <h4 class="text-center">La prochaine étape...</h4>
            <p class='text-center'>Pour pouvoir te conseiller au mieux, nous voulons apprendre à te connaître.</p>
            <p class='text-center'>Pour cela, rien de tel qu'une conversation de vive voix !</p>
            <%= link_to 'Je réserve un rendez-vous Skype !', "https://calendly.com/doitabroad/rendez-vous-telephonique", target: "_blank", class: "btn btn-sidebar" %>
        </div>
        <% end %>
        <div class="row">
          <ol class="wizard-progress text-center">

        <div class="col-xs-12 col-md-2">
        <% if @reservation.tracking_status == 'paid' || @reservation.tracking_status == 'meeting' || @reservation.tracking_status == 'suggestion' || @reservation.tracking_status == 'choice' || @reservation.tracking_status == 'inscription' %>
        <li class="active-step">
          <% else %>
          <li>
            <% end %>
            <span class="visuallyhidden">Step </span><span class="step-num">Paiement</span>
          </li>
        </div>

        <div class="col-xs-12 col-md-2">
        <% if @reservation.tracking_status == 'meeting' || @reservation.tracking_status == 'suggestion' || @reservation.tracking_status == 'choice' || @reservation.tracking_status == 'inscription' %>
        <li class="active-step">
          <% else %>
          <li>
            <% end %>
            <span class="visuallyhidden">Step </span><span class="step-num">Orientation</span>
          </li>
          </div>

          <div class="col-xs-12 col-md-2">
        <% if @reservation.tracking_status == 'suggestion' || @reservation.tracking_status == 'choice' || @reservation.tracking_status == 'inscription' %>
        <li class="active-step">
          <% else %>
          <li>
            <% end %>
            <span class="visuallyhidden">Step </span><span class="step-num">Propositions</span>
          </li>
        </div>

        <div class="col-xs-12 col-md-2">
        <% if @reservation.tracking_status == 'choice' || @reservation.tracking_status == 'inscription' %>
        <li class="active-step">
          <% else %>
          <li>
            <% end %>
            <span class="visuallyhidden">Step </span><span class="step-num">Choix de l'école</span>
          </li>
          </div>

          <div class="col-xs-12 col-md-2">
          <% if @reservation.tracking_status == 'inscription' %>
          <li class="active-step">
            <% else %>
            <li>
              <% end %>
              <span class="visuallyhidden">Step </span><span class="step-num">Inscription</span>
            </li>
          </div>
        </ol>
      </div>
      <% end %>
    </div>
  </div>
  <!-- /#page-content-wrapper -->
</div>

app/views/users/user_info.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="edit-headtitle">Afin d'obtenir les universités qui te correspondent le mieux, remplis ton profil !</h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="edit-form">
          <%= simple_form_for @user, :url => create_user_info_path, :method => :post do |f| %>
          <%= f.error_notification %>

          <%= f.input :first_name, required: true, autofocus: true, label: "Prénom" %>
          <%= f.input :last_name, required: true, label: "Nom" %>
          <%= f.input :birthday, :as=> 'string' ,:label => 'Date de naissance', input_html: { class: 'datepicker' } %>
          <%= f.input :email, required: true, label: "E-mail" %>
          <%= f.input :phone_number, required: true, label: "Téléphone" %>
          <%= f.input :study_level, as: :select, collection: @study_levels, required: true, label: "Niveau d'étude" %>
          <%= f.input :other_study_level, label: "Si autres, préciser" %>
          <%= f.input :specialisation, as: :select, collection: @specialisations, label: "Spécialité" %>
          <%= f.input :other_specialisation, label: "Si autres, préciser" %>
          <%= f.input :user_diploma,
                      as: :select,
                      collection: @user_diplomas,
                      label: "Diplôme souhaité",
                      hint: "Nous conseillons aux étudiants en Seconde, Première et Terminale de choisir Licence, aux étudiants en BTS et IUT de choisir Top-up, et aux étudiants en Licence et Master de choisir Master."
          %>
          <%= f.input :description, label: "Description de la spécialité recherchée" %>
          <%= f.input :favourite_pays, as: :select, collection: @pays, label: "Pays préféré (maximum 5)", include_blank: false, include_hidden: false, input_html: { multiple: 'multiple' } %>
          <%= f.input :budget, collection: @budget, label: "Budget maximum" %>
          <div class="submitbutton">
            <%= f.button :submit, "Valider mes informations" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>