config/routes.rb
Rails.application.routes.draw do
  # See all routes with "rails routes" command in terminal

  # Routes for rails_admin controller
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Routes for reservations controller
  resources :reservations, only: [:show, :new, :create, :edit, :update] do
    # Nested routes for payments controller
    resources :payments, only: [:new, :create]
  end

  # Routes for documents
  resources :documents, only: [:create]

  # Routes for custom users controller (not devise)
  resources :users, only: [:edit, :update]
  post '/create_user_info' => 'users#create_user_info', as: 'create_user_info'
  get '/users/:id/informations' => 'users#user_info', as: 'user_info'

  resources :user_data, only: [:new, :create, :update]
  # Routes for devise (user authentication)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Routes for pages controller
  root to: 'users#tracking'

  get '/tracking' => 'users#tracking', as: 'tracking'
  get '/profile' => 'user_data#profile', as: 'profile'
  get '/suggestions' => 'users#suggestions', as: 'suggestions'
  get '/accomodations' => 'users#accomodations', as: 'accomodations'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'logo-rose.png' %>
  </a>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if current_user %>
    <% if current_user.admin %>
    <%= link_to 'Admin', rails_admin_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <% if current_user.reservation != nil %>
    <% if current_user.reservation.payment_status == "paid" %>
    <%= link_to 'Mon dashboard', tracking_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <% end %>
    <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
    <% avatar_url = current_user.facebook_picture_url || current_user.profile_pic %>
    <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu"%>
    <% else %>
    <%= link_to 'Connexion', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Inscription', new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if current_user %>
        <%= link_to 'Déconnexion', destroy_user_session_path %>
        <% else %>
        <%= link_to 'Connexion', new_user_session_path %>
        <%= link_to 'Inscription', new_user_registration_path %>
        <% end %>
      </ul>
    </div>
  </div>
</div>