config/routes.rb
Rails.application.routes.draw do
  # See all routes with "rails routes" command in terminal

  # Routes for rails_admin controller
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Routes for reservations controller
  resources :reservations, only: [:show, :new, :create, :edit, :update] do
    # Nested routes for payments controller
    resources :payments, only: [:new, :create]
  end

  # Routes for documents
  resources :documents, only: [:create]

  # Routes for custom users controller (not devise)
  resources :users, only: [:edit, :update]
  post '/create_user_info' => 'users#create_user_info', as: 'create_user_info'
  get '/users/:id/informations' => 'users#user_info', as: 'user_info'

  resources :user_data, only: [:new, :create, :update]
  # Routes for devise (user authentication)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Routes for pages controller
  root to: 'users#tracking'

  get '/tracking' => 'users#tracking', as: 'tracking'
  get '/profile' => 'user_data#profile', as: 'profile'
  get '/suggestions' => 'users#suggestions', as: 'suggestions'
  get '/accomodations' => 'users#accomodations', as: 'accomodations'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :pack

  monetize :amount_cents

  # Defines a set of tracking statuses available (mainly for rails_admin interface)
  def tracking_status_enum
    [ "paid", "suggestion", "meeting", "choice", "inscription" ]
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:edit, :update]
  before_action :set_packs, only: [:new, :edit]
  before_action :set_chosen_pack, only: [:create, :update]

  # Display all three packs and invite user to choose one
  def new
    # Set a new reservation
    @reservation = Reservation.new
  end

  # Create a reservation with associated to the current user and chosen pack and redirect to payment
  def create
    # Create a reservation with selected pack informations
    @reservation  = Reservation.create!(pack_sku: @pack.sku, amount: @pack.price, payment_status: 'pending', tracking_status: 'pending', user_id: current_user.id, pack_id: @pack.id)

    # Redirect to payment page
    redirect_to new_reservation_payment_path(@reservation)
  end

  # Display all three packs and invite user to choose a new one
  def edit
  end

  # Update current user reservation with new pack infos and redirect to payment
  def update
    # Calculate new amount to pay with amount already paid by user (converted into Money object)
    @amount_to_pay = @pack.price - Money.new(current_user.paid_amount, 'EUR')

    # Update the reservation
    @reservation.update(pack_sku: @pack.sku, amount: @amount_to_pay, payment_status: 'pending', tracking_status: 'pending', pack_id: @pack.id)

    # Redirect to payment page
    redirect_to new_reservation_payment_path(@reservation)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:pack_id, :user_id)
  end

  # Set current user reservation for reservations#edit and reservations#update (see before_action above)
  def set_reservation
    @reservation = current_user.reservation
  end

  # Set all packs for reservations#new and reservations#edit (see before_action above)
  def set_packs
    @packs = Pack.all.sort_by {|pack| pack.id}
  end

  # Set pack selected by user for reservations#create and reservations#update (see before_action above)
  def set_chosen_pack
    @pack = Pack.find(params[:pack_id])
  end
end

app/views/reservations/edit.html.erb
<h1 class="text-center">Choisis l'accompagnement qui te convient !</h1>
<br>
<div class="row">
  <div class="card-deck">
    <% @packs.each do |pack| %>
    <div class="col-s-12 col-sm-4 card-container">
      <!-- <div class="container-fluid card-container"> -->
      <div class="card">
          <div class="card-block">
            <h4 class="card-title text-center"><%= pack.name.upcase %></h4>
            <br>
            <ul class="card-features">
              <% pack.features.each do |feature| %>
              <li><%= feature %></li>
              <br>
              <% end %>

            </ul>
          </div>
          <div class="card-footer text-center">
            <%= form_tag reservation_path, method: 'patch' do %>
            <%= hidden_field_tag 'pack_id', pack.id %>
            <%= submit_tag "#{humanized_money_with_symbol(pack.price)}", class:"btn btn-packs btn-danger", data: { confirm: 'Êtes-vous sûr de vouloir modifier votre réservation ?' } %>
            <% end %>
          </div>
          <!-- </div> -->
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<h1 class="text-center">Choisis l'accompagnement qui te convient !</h1>
<br>
<div class="row">
  <div class="card-deck">
    <% @packs.each do |pack| %>
    <div class="col-s-12 col-sm-4 card-container">
      <!-- <div class="container-fluid card-container"> -->
      <div class="card">
          <div class="card-block">
            <h4 class="card-title text-center"><%= pack.name.upcase %></h4>
            <br>
            <ul class="card-features">
              <% pack.features.each do |feature| %>
              <li><%= feature %></li>
              <br>
              <% end %>
            </ul>
          </div>
          <div class="card-footer text-center">
            <%= form_tag reservations_path do %>
            <%= hidden_field_tag 'pack_id', pack.id %>
            <%= submit_tag "#{humanized_money_with_symbol(pack.price)}", class:"btn btn-packs btn-danger", data: { confirm: 'Êtes-vous sûr de vouloir finaliser votre réservation ?' } %>
            <% end %>
          </div>
          <!-- </div> -->
      </div>
    </div>
    <% end %>
  </div>
</div>