config/routes.rb
Rails.application.routes.draw do
  # See all routes with "rails routes" command in terminal

  # Routes for rails_admin controller
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Routes for reservations controller
  resources :reservations, only: [:show, :new, :create, :edit, :update] do
    # Nested routes for payments controller
    resources :payments, only: [:new, :create]
  end

  # Routes for documents
  resources :documents, only: [:create]

  # Routes for custom users controller (not devise)
  resources :users, only: [:edit, :update]
  post '/create_user_info' => 'users#create_user_info', as: 'create_user_info'
  get '/users/:id/informations' => 'users#user_info', as: 'user_info'

  resources :user_data, only: [:new, :create, :update]
  # Routes for devise (user authentication)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Routes for pages controller
  root to: 'users#tracking'

  get '/tracking' => 'users#tracking', as: 'tracking'
  get '/profile' => 'user_data#profile', as: 'profile'
  get '/suggestions' => 'users#suggestions', as: 'suggestions'
  get '/accomodations' => 'users#accomodations', as: 'accomodations'
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_reservation

  # Displays a summary of the reservation and invites to pay
  def new
    @pack = @reservation.pack
  end

  # Create a new Stripe customer (for later use), pay via Stripe with user bank info and update the reservation statuses
  def create
    # Stripe customer creation
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
    )
    # Stripe payment
    charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @reservation.amount_cents,
    description:  "Paiement pour le pack #{@reservation.pack_sku} de la réservation #{@reservation.id}",
    currency:     @reservation.amount.currency
    )
    # Update the reservation statuses after payment is confirmed
    @reservation.update(payment: charge.to_json, payment_status: 'paid', tracking_status: 'paid')
    @reservation.save

    # Save paid amount in user profile (in case of pack modification, it will give ability to calculate amount to be paid)
    update_paid_amount(@reservation)

    # Redirect to user's dashboard
    redirect_to tracking_path

    # Send receipt E-mail
    send_receipt_mail

    # Redirect to payment page in case of error
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_reservation_payment_path(@reservation)
  end

  private

  # Sets the user's reservation
  def set_reservation
    @reservation = current_user.reservation
  end

  def send_receipt_mail
    my_token = ENV['POSTMARK_API_KEY']
    client = Postmark::ApiClient.new(my_token)
    client.deliver_with_template(from: 'info@do-it-abroad.com',
                             to: "#{current_user.email}",
                             template_id: 3382008,
                             template_model: {
                               name: "#{current_user.first_name}",
                             })
  end

  def update_paid_amount(reservation)
    current_user.paid_amount += reservation.amount_cents
    current_user.save
  end

end

app/views/payments/new.html.erb
<div class="container">
  <div class="row text-center">
    <h4 class="text-center">Récapitulatif de réservation</h4>
    <p class='center-align'>Votre réservation a été effectuée ! Si vous souhaitez la modifier, cliquez sur 'Changer de formule'.</p>
    <p class='center-align'>No worries mate ! Toutes vos informations pourront être modifiées plus tard, même la formule choisie. Elle est pas belle la vie ?</p>
  </div>
  <div class="row padded">
    <div class="col-xs-12 centered marged">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title text-center"><%= @pack.name.upcase %></h4>
          <br>
          <ul class="card-features">
            <% @pack.features.each do |feature| %>
            <li><%= feature %></li>
            <br>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </br>
  <div class="col-xs-12 marged text-center">
    <%= form_tag reservation_payments_path(@reservation) do %>
    <article>
      <label class="amount">
        <span>Total : <%= humanized_money_with_symbol(@reservation.amount) %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Ma réservation"
    data-email="<%= current_user.email %>"
    data-description="Réservation pour le pack <%= @reservation.pack_sku %>"
    data-amount="<%= @reservation.amount_cents %>"
    data-currency="<%= @reservation.amount.currency %>"></script>

    <% end %>
    <br>
    <%= link_to 'Changer de formule', edit_reservation_path(@reservation) %>
  </div>
</div>
</div>